version: "3.8"
services:
  app:
    image: ${REGISTRY}/${IMAGE}:${VERSION}
    command: >
      /bin/ash -c "
        node server
      "
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      PORT_PUBLISHED: ${PORT_PUBLISHED}
    ports:
      - ${PORT_PUBLISHED}:${PORT}
